// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDI9t5A121q6MSFA1HuiztrvbLWQFQjia4',
    appId: '1:1009155002224:web:441264cd3b50785d7ec9b5',
    messagingSenderId: '1009155002224',
    projectId: 'flutter-project-8a5e1',
    authDomain: 'flutter-project-8a5e1.firebaseapp.com',
    storageBucket: 'flutter-project-8a5e1.firebasestorage.app',
    measurementId: 'G-ZC0LJPZ2NC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArAWRtk1RO9XvXi5heQv_iiAURsHB-oCg',
    appId: '1:1009155002224:android:0ad64b4dd409c88c7ec9b5',
    messagingSenderId: '1009155002224',
    projectId: 'flutter-project-8a5e1',
    storageBucket: 'flutter-project-8a5e1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXhQ6PdgxDUJjDQG6IbZhptktLJfYgv70',
    appId: '1:1009155002224:ios:ef684d923e0630857ec9b5',
    messagingSenderId: '1009155002224',
    projectId: 'flutter-project-8a5e1',
    storageBucket: 'flutter-project-8a5e1.firebasestorage.app',
    iosBundleId: 'com.example.blockWishlistAndCartApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXhQ6PdgxDUJjDQG6IbZhptktLJfYgv70',
    appId: '1:1009155002224:ios:ef684d923e0630857ec9b5',
    messagingSenderId: '1009155002224',
    projectId: 'flutter-project-8a5e1',
    storageBucket: 'flutter-project-8a5e1.firebasestorage.app',
    iosBundleId: 'com.example.blockWishlistAndCartApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDI9t5A121q6MSFA1HuiztrvbLWQFQjia4',
    appId: '1:1009155002224:web:40f00ab5fb4a4c827ec9b5',
    messagingSenderId: '1009155002224',
    projectId: 'flutter-project-8a5e1',
    authDomain: 'flutter-project-8a5e1.firebaseapp.com',
    storageBucket: 'flutter-project-8a5e1.firebasestorage.app',
    measurementId: 'G-00V93ZT6KB',
  );
}
